# Generated by Django 4.2.7 on 2023-12-05 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0004_emailhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextEmailHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField(verbose_name='date')),
                ('schedule_time', models.TimeField(verbose_name='time')),
                ('periodic_gap_day', models.IntegerField()),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_app.subscriber')),
            ],
        ),
    ]
