# Generated by Django 4.2.7 on 2023-12-05 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0005_nextemailhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextemailhistory',
            name='schedule_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='nextemailhistory',
            name='schedule_time',
            field=models.TimeField(default=datetime.time(2, 13, 36, 180726)),
        ),
    ]
