# Generated by Django 4.2.7 on 2023-12-05 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0006_alter_nextemailhistory_schedule_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextemailhistory',
            name='schedule_time',
            field=models.TimeField(default=datetime.time(2, 14, 1, 931088)),
        ),
    ]
