# Generated by Django 4.2.7 on 2023-12-07 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0008_remove_subscriber_message_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailplusschedulemodel',
            name='schedule_time',
            field=models.TimeField(default='12-12-2023'),
        ),
        migrations.AlterField(
            model_name='nextemailhistory',
            name='schedule_time',
            field=models.TimeField(default=datetime.time(1, 46, 59, 646470)),
        ),
    ]
