# Generated by Django 4.2.7 on 2023-12-09 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0009_alter_emailplusschedulemodel_schedule_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailplusschedulemodel',
            name='gap',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='emailplusschedulemodel',
            name='schedule_time',
            field=models.TimeField(default=datetime.time(12, 58, 35, 71472)),
        ),
        migrations.AlterField(
            model_name='nextemailhistory',
            name='schedule_time',
            field=models.TimeField(default=datetime.time(12, 58, 35, 71472)),
        ),
    ]
