# Generated by Django 4.2.7 on 2023-12-09 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0010_alter_emailplusschedulemodel_gap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailplusschedulemodel',
            name='gap',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='emailplusschedulemodel',
            name='schedule_time',
            field=models.TimeField(default=datetime.time(13, 57, 53, 104938)),
        ),
        migrations.AlterField(
            model_name='nextemailhistory',
            name='schedule_time',
            field=models.TimeField(default=datetime.time(13, 57, 53, 89317)),
        ),
    ]
