# Generated by Django 4.2.7 on 2023-12-09 08:37

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0011_alter_emailplusschedulemodel_gap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailplusschedulemodel',
            name='schedule_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='nextemailhistory',
            name='schedule_time',
            field=models.TimeField(default=datetime.time(14, 7, 30, 762082)),
        ),
    ]
