# Generated by Django 4.2.7 on 2023-12-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0012_alter_emailplusschedulemodel_schedule_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailModel',
        ),
        migrations.AlterField(
            model_name='emailplusschedulemodel',
            name='schedule_time',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='NextEmailHistory',
        ),
    ]
